name: docs
on:
  push:
    branches: [ main ]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install poetry
        run: |
          pip install -U pip
          pip install poetry~=1.1.0
      - name: Install dependencies
        run: |
          poetry install
          poetry install -E pipenv -E poetry -E cookiecutter

      - name: Build and publish docs
        env:
          PYTHONPATH: docs
        run: |
          poetry run mkdocs gh-deploy --config-file docs/mkdocs.yml --force
